services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: ["node", "dist/server/index.js"]
    develop:
      watch:
        - action: rebuild
          path: ./src
